function DrawCallStressTestScene(){GraphicsTestBase.call(this,"Draw-call Stress Test",!0),this.drawCalls=0,this.calculator=new WorkloadCalculator(50,50,30),this.cameraSpeed=.6,this.fullDuration=0,this.fullFrames=0,this.numberOfRendersPerRenderLoop=4,this.updateTimePerRender=.05}function createMaterial(){var e=document.getElementById("shader").textContent,t="#define VERTEX_SHADER\n"+e,r="#define FRAGMENT_SHADER\n"+e
return new THREE.ShaderMaterial({attributes:{color:{type:"v3",value:[]}},wireframe:!0,vertexShader:t,fragmentShader:r})}function createGeometry(e){var t=new THREE.OBJLoader
t.load("assets/Plane.obj",function(t){var r
t.traverse(function(e){e instanceof THREE.Mesh&&(r=e.geometry)})
var a=null
a=e.demoMode===!0?BufferGeometryToBufferGeometryDef(r,r.getAttribute("position").array.length/3):BufferGeometryToBufferGeometryDef(r,16),e.onInitReady(a.geometry,a.batches,a.batchSize)})}DrawCallStressTestScene.prototype=Object.create(GraphicsTestBase.prototype),DrawCallStressTestScene.prototype.update=function(e){GraphicsTestBase.prototype.update.call(this,e),rotateCameraAroundPoint(this.camera,new THREE.Vector3(0,0,0),this.cameraSpeed*e*Math.PI)},DrawCallStressTestScene.prototype.initializeAssets=function(){GraphicsTestBase.prototype.initializeAssets.call(this),this.demoMode===!0?this.setRenderFrameCount(50*this.numberOfRendersPerRenderLoop):this.setRenderFrameCount(10*this.numberOfRendersPerRenderLoop),createGeometry(this)},DrawCallStressTestScene.prototype.createScene=function(){GraphicsTestBase.prototype.createScene.call(this),this.demoMode===!0?this.setDrawCallCount(1,1):this.setDrawCallCount(1,this.calculator.getWorkload())
for(var e=this.calculator.getScores(),t=Object.keys(e),r="",a=0;a<t.length;++a){var s=t[a]
r+=s+", score: "+e[s].score+" wl: "+e[s].workload+" sd; "+e[s].variance+"\n"}r+=" next workload: "+this.calculator.getWorkload(),this.showInfo(r)},DrawCallStressTestScene.prototype.renderLoopResultsReceived=function(e,t){this.calculator.reportCurrentWorkloadScore(t/(.001*e)),this.fullDuration=this.fullDuration+e,this.fullFrames=this.fullFrames+t},DrawCallStressTestScene.prototype.shouldRestartRenderLoop=function(){if(this.demoMode===!0)return!1
var e=this.calculator.isTargetScoreReceived(),t=this.calculator.runsDoneForCurrentWorkload()
return!e&&t>0},DrawCallStressTestScene.prototype.shouldRecreateScene=function(){return this.demoMode===!0?!1:!this.calculator.isTargetScoreReceived()},DrawCallStressTestScene.prototype.testCompleted=function(){for(var e=BasemarkWebEngine.getElapsedTime(),t=this.calculator.getScores(),r=Object.keys(t),a="",s=0;s<r.length;++s){var o=r[s]
a+=o+", score: "+t[o].score+" wl: "+t[o].workload+" sd; "+t[o].variance+"\n"}this.showInfo(a),BasemarkWebEngine.submitResult(t.peak.workload,guide,t,e,t.peak.score,-1),BasemarkWebEngine.nextPage(location.pathname)},DrawCallStressTestScene.prototype.onInitReady=function(e,t,r){this.material=createMaterial(),this.objects=[],this.protoGeometry=e,this.geometryBatchCount=t,this.geometryBatchSize=r,this.scene=new THREE.Scene,this.camera=new THREE.PerspectiveCamera(75,window.innerWidth/window.innerHeight,.01,1e3),this.renderer=new THREE.WebGLRenderer,this.renderer.setSize(window.innerWidth,window.innerHeight),this.renderer.autoClear=!1,this.renderer.setClearColor(0),document.getElementById(testContainerName).appendChild(this.renderer.domElement),this.camera.position.set(0,0,400),this.assetInitializationDone()},DrawCallStressTestScene.prototype.setupTransform=function(e,t){var r=.3
e.scale.set(r,r,r)},DrawCallStressTestScene.prototype.setDrawCallCount=function(e,t){this.objects.length=0,delete this.scene,this.scene=new THREE.Scene
for(var r=[],a=this.geometryBatchSize,s=0;t>s;++s){s>=this.geometryBatchCount
var o=s%this.geometryBatchCount
r.push({count:a,start:0,index:o*a})}this.protoGeometry.offsets=r,this.protoGeometry.drawcalls=r
for(var s=0;e>s;++s){var n=new THREE.Mesh(this.protoGeometry,this.material)
this.setupTransform(n,s),n.matrixAutoUpdate=!1,n.rotationAutoUpdate=!1,n.updateMatrix(),this.scene.add(n)}}
